### ISSUE TITLE
Memory usage auditing?

### ISSUE THREAD

**Issue by crlf0710** [image-rs/canvas#2]
Hi, this work is definitely interesting! After reading the API surface, one thing that comes up to my mind is that the panicking behavior is sub-optimal. There should be some "checked" canvas creation, which returns `Err` on failure to creation. this may be caused by incorrect user setting, large working set or the application is simply trying to allocate as many as it can.

So i think there should be some auditing support, e.g. Whenever you try to allocate, the Canvas can calculate the buffer size it will need and submit to it. It checks its quota to see if such allocation is allowed, if it is allowed, the Canvas is created, otherwise the allocation is forbidden and Canvas creation fails.

**Comment by HeroicKatora** [comment]
I currently planned to offload this auditing of size to the programmer, similar to `Vec` etc. For that purpose, [`Layout::byte_len`](https://docs.rs/image-canvas/0.0.1/canvas/struct.Layout.html#method.byte_len) is publicly exported and `Canvas::with_width_and_height` is supposed to merely be convenience wrappers around it (it is internally anyways) when no error is expected or it is fine to panic. This creates two basic APIs: One brief, and simple for safe context where no malicious input is expected and one which allows greater control over the operations–including resource checks–but requires lengthier checks. 

The main reason to keep this outside of this crate is that it should only provide mechanisms, and no policy, and stay as generic and contained as possible. Since I did not find a clear and unique definition for bounds checking (should individual sizes be checked? the total size? runtime?, ...) it aims to make all flavours of bounds checking possible but not perform them itself.

As soon as the `try_` variants of allocating `Vec` are stable enough, I'll consider having the same in `Rec` and by extension the other types.

**Comment by HeroicKatora** [comment]
I suppose the documentation should stress this more clearly, so that `image` libraries parsing untrusted input know where to look for the checked and non-panicking variants.

**Comment by crlf0710** [comment]
Thanks!

**Comment by HeroicKatora** [comment]
The documentation as added in https://github.com/image-rs/canvas/commit/09b0b918755941498aa14201e02fe8e78e56d609 so I'm closing this. With the addition of `realloc` a similar issue will be solved in the same manner. If there are any specific instances of the documentation lacking feel free to open them as separate issue,
